"""Supplemental canonical sheaf artifacts.

These artifacts deepen existing canonical tracks without adding new live track
ids.  They are generated by ``generate_sheaf_tracks.py`` and validated as
artifact-level proof surfaces.
"""

from __future__ import annotations

import hashlib
import json
import re
from collections import defaultdict
from pathlib import Path
from typing import Any

from json_io import load_json as _load_json
from json_io import write_json as _write_json

SUPPLEMENTAL_ARTIFACTS: dict[str, str] = {
    "proof_dependency_graph": "output/data/proof_dependency_graph.json",
    "state_transition_table": "output/data/state_transition_table.json",
    "ablation_sensitivity_report": "output/reports/ablation_sensitivity_report.json",
    "release_attestation": "output/reports/release_attestation.json",
}


def _sha256(path: Path) -> str:
    if not path.is_file():
        return ""
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _statement_symbols(statement: str) -> list[str]:
    """Extract stable statement identifiers from a Lean theorem statement."""
    stop = {
        "True",
        "False",
        "Nat",
        "Int",
        "Float",
        "Prop",
        "by",
        "theorem",
    }
    symbols = {
        token
        for token in re.findall(r"[A-Za-z_][A-Za-z0-9_']*", statement)
        if token not in stop and not token[0].isdigit()
    }
    return sorted(symbols)


def build_proof_dependency_graph(project_root: Path) -> dict[str, Any]:
    """Build theorem-to-source, theorem-to-symbol, and theorem-to-witness edges."""
    root = project_root.resolve()
    proof = _load_json(root / "output" / "data" / "proof_extraction_index.json")
    theorem_trace = _load_json(root / "output" / "data" / "theorem_traceability_matrix.json")
    trace_by_theorem = {row.get("theorem"): row for row in theorem_trace.get("rows") or []}
    rows: list[dict[str, Any]] = []
    edges: list[dict[str, str]] = []
    for proof_row in proof.get("rows") or []:
        theorem = str(proof_row.get("theorem") or "")
        source = str(proof_row.get("source") or "")
        statement = str(proof_row.get("statement") or "")
        tactic = str(proof_row.get("leading_tactic") or "no_leading_tactic")
        symbols = _statement_symbols(statement)
        trace_row = trace_by_theorem.get(theorem, {})
        witnesses = [str(value) for value in trace_row.get("model_witnesses") or [] if value]
        rows.append(
            {
                "theorem": theorem,
                "source": source,
                "leading_tactic": tactic,
                "statement_symbol_count": len(symbols),
                "statement_symbols": symbols,
                "witness_count": len(witnesses),
                "linked": bool(source and statement and symbols and trace_row.get("linked") is True),
            }
        )
        edges.append({"source": theorem, "target": source, "kind": "theorem_to_source"})
        edges.append({"source": theorem, "target": f"lean_tactic:{tactic}", "kind": "theorem_to_tactic"})
        for symbol in symbols:
            edges.append({"source": theorem, "target": symbol, "kind": "theorem_to_definition"})
        for witness in witnesses:
            edges.append({"source": theorem, "target": witness, "kind": "theorem_to_model_witness"})
    edge_types = sorted({edge["kind"] for edge in edges})
    return {
        "schema": "template_active_inference.proof_dependency_graph.v1",
        "rows": rows,
        "edges": edges,
        "theorem_count": len(rows),
        "edge_count": len(edges),
        "edge_types": edge_types,
        "required_edge_types": [
            "theorem_to_source",
            "theorem_to_tactic",
            "theorem_to_definition",
            "theorem_to_model_witness",
        ],
        "all_theorems_have_dependencies": bool(rows) and all(row["linked"] for row in rows),
        "all_edges_resolved": bool(edges) and all(edge["source"] and edge["target"] and edge["kind"] for edge in edges),
    }


def _graph_world_transition_rows(root: Path) -> list[dict[str, Any]]:
    traces = _load_json(root / "output" / "data" / "si_graph_world_topology_traces.json")
    rows: list[dict[str, Any]] = []
    for topology in traces.get("rows") or []:
        topology_id = str(topology.get("topology") or "")
        trace = topology.get("trace") or []
        for current, nxt in zip(trace, trace[1:], strict=False):
            rows.append(
                {
                    "model": f"graph_world_{topology_id}",
                    "state": str(current.get("node") or ""),
                    "action": str(current.get("action") or "advance"),
                    "next_state": str(nxt.get("node") or ""),
                    "reachable": True,
                    "deterministic": True,
                    "source": "output/data/si_graph_world_topology_traces.json",
                }
            )
        if trace:
            terminal = str(trace[-1].get("node") or "")
            rows.append(
                {
                    "model": f"graph_world_{topology_id}",
                    "state": terminal,
                    "action": "stay_goal",
                    "next_state": terminal,
                    "reachable": True,
                    "deterministic": True,
                    "source": "output/data/si_graph_world_topology_traces.json",
                }
            )
    return rows


def _tmaze_transition_rows() -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    table = {
        ("start", "observe_cue"): "cue",
        ("start", "advance"): "cue",
        ("cue", "choose_left"): "goal",
        ("cue", "choose_right"): "goal",
        ("goal", "choose_left"): "goal",
        ("goal", "choose_right"): "goal",
    }
    for (state, action), next_state in table.items():
        rows.append(
            {
                "model": "si_tmaze",
                "state": state,
                "action": action,
                "next_state": next_state,
                "reachable": True,
                "deterministic": True,
                "source": "output/data/si_tmaze_summary.json",
            }
        )
    return rows


def build_state_transition_table(project_root: Path) -> dict[str, Any]:
    """Build explicit finite transition rows for graph-world topologies and T-maze actions."""
    root = project_root.resolve()
    catalog = _load_json(root / "output" / "data" / "state_space_catalog.json")
    rows = _graph_world_transition_rows(root) + _tmaze_transition_rows()
    models_with_rows = {row["model"] for row in rows}
    required_models = {
        str(row.get("model"))
        for row in catalog.get("rows") or []
        if str(row.get("model") or "").startswith(("graph_world_", "si_tmaze"))
    }
    return {
        "schema": "template_active_inference.state_transition_table.v1",
        "rows": rows,
        "row_count": len(rows),
        "model_count": len(models_with_rows),
        "required_models": sorted(required_models),
        "covered_models": sorted(models_with_rows),
        "all_transitions_deterministic": bool(rows) and all(row["deterministic"] for row in rows),
        "all_reachable_states_covered": bool(required_models) and required_models.issubset(models_with_rows),
    }


def build_ablation_sensitivity_report(project_root: Path) -> dict[str, Any]:
    """Join causal-ablation effects to sensitivity and uncertainty source rows."""
    root = project_root.resolve()
    ablation = _load_json(root / "output" / "data" / "causal_ablation_matrix.json")
    sensitivity = _load_json(root / "output" / "data" / "sensitivity_sweep.json")
    uncertainty = _load_json(root / "output" / "data" / "uncertainty_summary.json")
    sensitivity_by_key: dict[tuple[str, float], list[dict[str, Any]]] = defaultdict(list)
    for row in sensitivity.get("rows") or []:
        sensitivity_by_key[(str(row.get("topology") or ""), float(row.get("lambda", 0.0) or 0.0))].append(row)
    uncertainty_rows = uncertainty.get("rows") or []
    rows: list[dict[str, Any]] = []
    for row in ablation.get("rows") or []:
        key = (str(row.get("topology") or ""), float(row.get("lambda", 0.0) or 0.0))
        linked = sensitivity_by_key.get(key, [])
        mi_values = [float(item.get("mi", 0.0) or 0.0) for item in linked]
        rows.append(
            {
                "topology": key[0],
                "lambda": key[1],
                "perturbation": row.get("perturbation", ""),
                "metric": row.get("metric", ""),
                "effect": float(row.get("effect", 0.0) or 0.0),
                "sensitivity_row_count": len(linked),
                "mean_sensitivity_mi": sum(mi_values) / len(mi_values) if mi_values else 0.0,
                "uncertainty_row_count": len(uncertainty_rows),
                "ablation_source": "output/data/causal_ablation_matrix.json",
                "sensitivity_source": "output/data/sensitivity_sweep.json",
                "uncertainty_source": "output/data/uncertainty_summary.json",
                "source_backed": bool(linked and uncertainty_rows and row.get("source")),
            }
        )
    max_abs_effect = max((abs(row["effect"]) for row in rows), default=0.0)
    return {
        "schema": "template_active_inference.ablation_sensitivity_report.v1",
        "rows": rows,
        "row_count": len(rows),
        "max_abs_effect": max_abs_effect,
        "source_artifacts": [
            "output/data/causal_ablation_matrix.json",
            "output/data/sensitivity_sweep.json",
            "output/data/uncertainty_summary.json",
        ],
        "all_effects_source_backed": bool(rows) and all(row["source_backed"] for row in rows),
    }


def build_release_attestation(project_root: Path) -> dict[str, Any]:
    """Attest release bundle, validation, license, and blocked-scope status."""
    root = project_root.resolve()
    validation_path = root / "output" / "reports" / "validation_report.json"
    release_path = root / "output" / "reports" / "release_bundle_manifest.json"
    semantic_path = root / "output" / "data" / "sheaf_gluing_certificate.json"
    validation = _load_json(validation_path)
    release = _load_json(root / "output" / "reports" / "release_bundle_manifest.json")
    license_audit = _load_json(root / "output" / "reports" / "artifact_license_audit.json")
    blocked = _load_json(root / "output" / "reports" / "blocked_scope_manifest.json")
    visualization = _load_json(root / "output" / "reports" / "visualization_quality_audit.json")
    statistical_bridge = _load_json(root / "output" / "data" / "statistical_visualization_bridge.json")
    semantic = _load_json(semantic_path)
    validation_deferred = not validation_path.is_file()
    if validation_path.is_file() and release_path.is_file():
        validation_deferred = validation_path.stat().st_mtime < release_path.stat().st_mtime
    semantic_false_restrictions = [key for key, value in (semantic.get("restrictions") or {}).items() if value is False]
    semantic_non_self_false = [
        restriction for restriction in semantic_false_restrictions if restriction != "release_attestation_complete"
    ]
    semantic_passed = semantic.get("ok") is True or (bool(semantic.get("restrictions")) and not semantic_non_self_false)
    validation_passed = (
        validation.get("all_passed") is True
        or validation.get("ok") is True
        or (validation.get("summary") or {}).get("all_passed") is True
    )
    rows = [
        {
            "id": "validation_report",
            "source": "output/reports/validation_report.json",
            "passed": validation_passed if not validation_deferred else False,
            "deferred_until_validation": validation_deferred,
        },
        {
            "id": "release_bundle",
            "source": "output/reports/release_bundle_manifest.json",
            "passed": release.get("all_required_sources_present") is True
            and release.get("all_copied_outputs_match_or_deferred") is True,
            "bundle_hash": release.get("bundle_hash", ""),
            "deferred_until_validation": False,
        },
        {
            "id": "artifact_license",
            "source": "output/reports/artifact_license_audit.json",
            "passed": license_audit.get("all_license_safe") is True,
            "deferred_until_validation": False,
        },
        {
            "id": "blocked_scope",
            "source": "output/reports/blocked_scope_manifest.json",
            "passed": blocked.get("all_blocked") is True,
            "deferred_until_validation": False,
        },
        {
            "id": "visualization_quality",
            "source": "output/reports/visualization_quality_audit.json",
            "passed": visualization.get("all_quality_ok") is True
            and visualization.get("all_sources_mapped") is True
            and visualization.get("all_rendered") is True
            and visualization.get("all_accessibility_text_ok") is True
            and visualization.get("all_hashes_present") is True
            and visualization.get("all_visual_roles_present") is True
            and visualization.get("all_evidence_roles_present") is True
            and visualization.get("all_paper_claims_present") is True
            and visualization.get("all_figures_section_bound") is True
            and visualization.get("all_statistical_sources_present") is True
            and int(visualization.get("statistically_backed_count", 0) or 0) >= 6,
            "statistical_bridge_passed": visualization.get("all_statistical_sources_present") is True
            and int(visualization.get("statistically_backed_count", 0) or 0) >= 6,
            "deferred_until_validation": False,
        },
        {
            "id": "statistical_visualization_bridge",
            "source": "output/data/statistical_visualization_bridge.json",
            "passed": statistical_bridge.get("all_rows_connected") is True
            and statistical_bridge.get("all_statistical_sources_present") is True
            and statistical_bridge.get("all_figures_referenced") is True
            and statistical_bridge.get("all_reference_sections_sheaf_bound") is True
            and statistical_bridge.get("all_reference_sections_visualization_bound") is True
            and statistical_bridge.get("all_sheaf_tracks_registered") is True
            and int(statistical_bridge.get("row_count", 0) or 0) >= 6,
            "deferred_until_validation": False,
        },
        {
            "id": "semantic_certificate",
            "source": "output/data/sheaf_gluing_certificate.json",
            "passed": semantic_passed,
            "ignored_self_restrictions": (
                ["release_attestation_complete"]
                if "release_attestation_complete" in semantic_false_restrictions
                else []
            ),
            "deferred_until_validation": False,
        },
    ]
    return {
        "schema": "template_active_inference.release_attestation.v1",
        "rows": rows,
        "row_count": len(rows),
        "bundle_hash": release.get("bundle_hash", ""),
        "attestation_hash": hashlib.sha256(json.dumps(rows, sort_keys=True).encode("utf-8")).hexdigest(),
        "all_attested": all(row["passed"] or row["deferred_until_validation"] for row in rows),
    }


def write_supplemental_artifacts(project_root: Path) -> dict[str, Path]:
    """Write all supplemental canonical sheaf artifacts."""
    root = project_root.resolve()
    return {
        "proof_dependency_graph": _write_json(
            root / SUPPLEMENTAL_ARTIFACTS["proof_dependency_graph"],
            build_proof_dependency_graph(root),
        ),
        "state_transition_table": _write_json(
            root / SUPPLEMENTAL_ARTIFACTS["state_transition_table"],
            build_state_transition_table(root),
        ),
        "ablation_sensitivity_report": _write_json(
            root / SUPPLEMENTAL_ARTIFACTS["ablation_sensitivity_report"],
            build_ablation_sensitivity_report(root),
        ),
        "release_attestation": _write_json(
            root / SUPPLEMENTAL_ARTIFACTS["release_attestation"],
            build_release_attestation(root),
        ),
    }


def validate_supplemental_artifacts(project_root: Path) -> list[str]:
    """Validate supplemental artifacts from row-derived conditions."""
    root = project_root.resolve()
    issues: list[str] = []
    proof = _load_json(root / SUPPLEMENTAL_ARTIFACTS["proof_dependency_graph"])
    if proof.get("schema") != "template_active_inference.proof_dependency_graph.v1":
        issues.append("proof_dependency_graph.json schema mismatch")
    proof_rows = proof.get("rows") or []
    proof_edges = proof.get("edges") or []
    proof_rows_ok = bool(proof_rows) and all(row.get("linked") for row in proof_rows)
    proof_edges_ok = bool(proof_edges) and all(
        edge.get("source") and edge.get("target") and edge.get("kind") for edge in proof_edges
    )
    if (
        proof.get("all_theorems_have_dependencies") is not True
        or proof.get("all_theorems_have_dependencies") != proof_rows_ok
    ):
        issues.append("proof_dependency_graph.json has unlinked theorem dependencies")
    if proof.get("all_edges_resolved") is not True or proof.get("all_edges_resolved") != proof_edges_ok:
        issues.append("proof_dependency_graph.json has unresolved edges")

    transitions = _load_json(root / SUPPLEMENTAL_ARTIFACTS["state_transition_table"])
    if transitions.get("schema") != "template_active_inference.state_transition_table.v1":
        issues.append("state_transition_table.json schema mismatch")
    transition_rows = transitions.get("rows") or []
    deterministic = bool(transition_rows) and all(
        row.get("deterministic") and row.get("next_state") for row in transition_rows
    )
    covered = set(transitions.get("required_models") or []).issubset(set(transitions.get("covered_models") or []))
    if (
        transitions.get("all_transitions_deterministic") is not True
        or transitions.get("all_transitions_deterministic") != deterministic
    ):
        issues.append("state_transition_table.json has nondeterministic or incomplete transitions")
    if (
        transitions.get("all_reachable_states_covered") is not True
        or transitions.get("all_reachable_states_covered") != covered
    ):
        issues.append("state_transition_table.json omits a reachable finite model")

    ablation = _load_json(root / SUPPLEMENTAL_ARTIFACTS["ablation_sensitivity_report"])
    if ablation.get("schema") != "template_active_inference.ablation_sensitivity_report.v1":
        issues.append("ablation_sensitivity_report.json schema mismatch")
    ablation_rows = ablation.get("rows") or []
    ablation_backed = bool(ablation_rows) and all(row.get("source_backed") for row in ablation_rows)
    if (
        ablation.get("all_effects_source_backed") is not True
        or ablation.get("all_effects_source_backed") != ablation_backed
    ):
        issues.append("ablation_sensitivity_report.json has unsupported ablation effects")

    attestation = _load_json(root / SUPPLEMENTAL_ARTIFACTS["release_attestation"])
    if attestation.get("schema") != "template_active_inference.release_attestation.v1":
        issues.append("release_attestation.json schema mismatch")
    attestation_rows = attestation.get("rows") or []
    attested = bool(attestation_rows) and all(
        row.get("passed") or row.get("deferred_until_validation") for row in attestation_rows
    )
    if attestation.get("all_attested") is not True or attestation.get("all_attested") != attested:
        issues.append("release_attestation.json claims a failed gate passed")
    return issues
