"""Artifact path SSOT."""

from __future__ import annotations

PROMOTED_ARTIFACTS: dict[str, str] = {
    "sensitivity": "output/data/sensitivity_sweep.json",
    "uncertainty": "output/data/uncertainty_summary.json",
    "benchmark": "output/data/toy_benchmark_matrix.json",
    "policy_grid": "output/data/si_policy_grid.json",
    "efe_terms": "output/data/si_efe_terms.json",
    "topology": "output/data/si_graph_world_topology_sweep.json",
    "topology_traces": "output/data/si_graph_world_topology_traces.json",
    "graph_invariants": "output/reports/graph_world_invariants.json",
    "observable": "output/data/analytical_observable_sweep.json",
    "model_checking": "output/reports/model_checking_witnesses.json",
    "interop": "output/data/interop_roundtrip_report.json",
    "gnn_roundtrip": "output/data/gnn_roundtrip_report.json",
    "gnn_lint": "output/reports/gnn_lint_report.json",
    "ontology_alias": "output/data/ontology_alias_index.json",
    "ontology_profile": "output/data/ontology_profile_matrix.json",
    "lean_theorems": "output/reports/lean_theorem_inventory.json",
    "lean_graph": "output/reports/lean_graph_world_inventory.json",
    "producer_completeness": "output/reports/producer_completeness.json",
    "stale_report": "output/reports/stale_artifact_report.json",
    "manuscript_staleness": "output/reports/manuscript_staleness_report.json",
    "cross_symbols": "output/data/cross_track_symbol_table.json",
    "evidence_tables": "output/data/manuscript_evidence_tables.json",
    "token_provenance": "output/data/manuscript_token_provenance.json",  # nosec B105
    "claim_audit": "output/reports/claim_evidence_audit.json",
    "gate_index": "output/data/validation_gate_index.json",
    "section_status": "output/data/sheaf_section_status_matrix.json",
    "render_log": "output/reports/sheaf_render_log.json",
    "figure_source": "output/data/figure_source_map.json",
    "figure_hash": "output/reports/figure_hash_manifest.json",
    "visualization_quality": "output/reports/visualization_quality_audit.json",
    "statistical_bridge": "output/data/statistical_visualization_bridge.json",
    "scope": "output/reports/scope_boundary_audit.json",
    "adversarial": "output/reports/adversarial_audit.json",
    "assumptions": "output/data/analytical_assumption_index.json",
    "animation_deltas": "output/data/animation_frame_deltas.json",
    "replay_matrix": "output/reports/replay_matrix.json",
    "track_lane_matrix": "output/data/track_lane_matrix.json",
    "artifact_contract_index": "output/data/artifact_contract_index.json",
    "track_scope": "output/data/track_improvement_scope.json",
    "blocked_scope": "output/reports/blocked_scope_manifest.json",
    "evidence_fields": "output/data/evidence_field_index.json",
    "release_bundle": "output/reports/release_bundle_manifest.json",
    "theorem_traceability": "output/data/theorem_traceability_matrix.json",
    "artifact_diffoscope": "output/reports/artifact_diffoscope.json",
    "proof_extraction": "output/data/proof_extraction_index.json",
    "state_space_catalog": "output/data/state_space_catalog.json",
    "causal_ablation": "output/data/causal_ablation_matrix.json",
    "artifact_license": "output/reports/artifact_license_audit.json",
    "release_notes": "output/reports/release_notes_evidence.json",
    "scholarship": "output/data/scholarship_source_matrix.json",
    "security_posture": "output/reports/security_posture_audit.json",
    "proof_dependency": "output/data/proof_dependency_graph.json",
    "transition_table": "output/data/state_transition_table.json",
    "ablation_sensitivity": "output/reports/ablation_sensitivity_report.json",
    "release_attestation": "output/reports/release_attestation.json",
}

VARIABLE_ARTIFACTS: dict[str, str] = {
    "policy": "output/data/si_policy_comparison.json",
    "posterior": "output/data/pymdp_policy_posterior_grid.json",
    "runtime": "output/reports/pymdp_runtime_diagnostics.json",
    "graph": "output/data/si_graph_world_summary.json",
    "graph_topology_traces": "output/data/si_graph_world_topology_traces.json",
    "provenance": "output/data/artifact_provenance.json",
    "replay": "output/reports/reproducibility_replay.json",
    "counterexample": "output/reports/counterexample_matrix.json",
    "sensitivity": "output/data/sensitivity_sweep.json",
    "uncertainty": "output/data/uncertainty_summary.json",
    "benchmark": "output/data/toy_benchmark_matrix.json",
    "model_checking": "output/reports/model_checking_witnesses.json",
    "lean_graph": "output/reports/lean_graph_world_inventory.json",
    "interop": "output/data/interop_roundtrip_report.json",
    "adversarial": "output/reports/adversarial_audit.json",
    "semantic": "output/data/sheaf_gluing_certificate.json",
    "dependency": "output/data/validation_dependency_graph.json",
    "stale": "output/reports/stale_artifact_report.json",
    "manuscript_staleness": "output/reports/manuscript_staleness_report.json",
    "figure_source": "output/data/figure_source_map.json",
    "visualization_quality": "output/reports/visualization_quality_audit.json",
    "statistical_bridge": "output/data/statistical_visualization_bridge.json",
    "scope": "output/reports/scope_boundary_audit.json",
    "gate_index": "output/data/validation_gate_index.json",
    "section_status": "output/data/sheaf_section_status_matrix.json",
    "render_log": "output/reports/sheaf_render_log.json",
    "claim_audit": "output/reports/claim_evidence_audit.json",
    "token_provenance": "output/data/manuscript_token_provenance.json",  # nosec B105
    "cross_symbol": "output/data/cross_track_symbol_table.json",
    "assumption": "output/data/analytical_assumption_index.json",
    "animation_delta": "output/data/animation_frame_deltas.json",
    "replay_matrix": "output/reports/replay_matrix.json",
    "track_lane": "output/data/track_lane_matrix.json",
    "artifact_contract": "output/data/artifact_contract_index.json",
    "track_scope": "output/data/track_improvement_scope.json",
    "blocked_scope": "output/reports/blocked_scope_manifest.json",
    "evidence_fields": "output/data/evidence_field_index.json",
    "release_bundle": "output/reports/release_bundle_manifest.json",
    "theorem_traceability": "output/data/theorem_traceability_matrix.json",
    "artifact_diffoscope": "output/reports/artifact_diffoscope.json",
    "proof_extraction": "output/data/proof_extraction_index.json",
    "state_space_catalog": "output/data/state_space_catalog.json",
    "causal_ablation": "output/data/causal_ablation_matrix.json",
    "artifact_license": "output/reports/artifact_license_audit.json",
    "release_notes": "output/reports/release_notes_evidence.json",
    "scholarship": "output/data/scholarship_source_matrix.json",
    "security_posture": "output/reports/security_posture_audit.json",
    "proof_dependency": "output/data/proof_dependency_graph.json",
    "state_transition": "output/data/state_transition_table.json",
    "ablation_sensitivity": "output/reports/ablation_sensitivity_report.json",
    "release_attestation": "output/reports/release_attestation.json",
}

REQUIRED_GATE_ARTIFACTS: tuple[str, ...] = (
    "output/data/parameter_sweep.csv",
    "output/data/si_tmaze_summary.json",
    "output/data/si_tmaze_trace.json",
    "output/data/si_policy_comparison.json",
    "output/data/si_efe_terms.json",
    "output/data/pymdp_policy_posterior_grid.json",
    "output/reports/pymdp_runtime_diagnostics.json",
    "output/reports/si_invariants.json",
    "output/data/si_graph_world_summary.json",
    "output/data/si_graph_world_trace.json",
    "output/data/analysis_statistics.json",
    "output/data/sheaf_coverage_matrix.json",
    "output/data/artifact_provenance.json",
    "output/data/manuscript_variables.json",
    "output/data/sheaf_gluing_certificate.json",
    "output/data/sensitivity_sweep.json",
    "output/data/analytical_assumption_index.json",
    "output/data/si_graph_world_topology_traces.json",
    "output/data/uncertainty_summary.json",
    "output/data/toy_benchmark_matrix.json",
    "output/data/interop_roundtrip_report.json",
    "output/reports/model_checking_witnesses.json",
    "output/reports/adversarial_audit.json",
    "output/reports/replay_matrix.json",
    "output/data/track_lane_matrix.json",
    "output/data/artifact_contract_index.json",
    "output/data/track_improvement_scope.json",
    "output/reports/blocked_scope_manifest.json",
    "output/data/evidence_field_index.json",
    "output/reports/release_bundle_manifest.json",
    "output/data/theorem_traceability_matrix.json",
    "output/reports/artifact_diffoscope.json",
    "output/data/proof_extraction_index.json",
    "output/data/state_space_catalog.json",
    "output/data/causal_ablation_matrix.json",
    "output/reports/artifact_license_audit.json",
    "output/reports/release_notes_evidence.json",
    "output/reports/security_posture_audit.json",
    "output/data/proof_dependency_graph.json",
    "output/data/state_transition_table.json",
    "output/reports/ablation_sensitivity_report.json",
    "output/reports/release_attestation.json",
    "output/data/validation_gate_index.json",
    "output/data/validation_dependency_graph.json",
    "output/data/sheaf_section_status_matrix.json",
    "output/reports/sheaf_render_log.json",
    "output/reports/visualization_quality_audit.json",
    "output/data/statistical_visualization_bridge.json",
    "output/figures/semantic_gluing_graph.png",
    "output/figures/track_lane_promotion_map.png",
    "output/figures/artifact_contract_map.png",
    "output/figures/si_belief_trajectory.gif",
    "output/data/animation_frame_deltas.json",
    "output/reports/manuscript_staleness_report.json",
    "output/reports/reproducibility_replay.json",
    "output/reports/counterexample_matrix.json",
    "output/figures/theorem_traceability_graph.png",
    "output/figures/causal_ablation_heatmap.png",
    "output/figures/security_posture_map.png",
)

EXPERIMENT_PLAN_METRIC_KEYS: tuple[str, ...] = (
    "figures_nonblank",
    "toy_sweep_track_schemas",
    "analysis_statistics_schema",
    "formal_interop_track_schemas",
    "integration_audit_track_schemas",
    "animation_frame_deltas_schema",
    "pymdp_policy_posterior_grid_schema",
    "pymdp_runtime_diagnostics_schema",
    "si_graph_world_topology_traces_schema",
    "canonical_sheaf_track_schemas",
    "artifact_contract_index_schema",
    "visualization_quality_audit_schema",
    "statistical_visualization_bridge_schema",
    "sheaf_section_status_matrix_schema",
    "sheaf_render_log_schema",
    "artifact_diffoscope_schema",
    "proof_extraction_index_schema",
    "state_space_catalog_schema",
    "causal_ablation_matrix_schema",
    "artifact_license_audit_schema",
    "release_notes_evidence_schema",
    "scholarship_source_matrix_schema",
    "security_posture_audit_schema",
    "proof_dependency_graph_schema",
    "state_transition_table_schema",
    "ablation_sensitivity_report_schema",
    "release_attestation_schema",
)
